[package]
name = "chartapi"
version = "0.1.0"
authors = ["Attila Kun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.2"
chart = { path = "../chart" }
iex = { path = "../iex" }