[package]
name = "chartapi"
version = "0.1.0"
authors = ["Attila Kun"]
edition = "2018"

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.2"
chart = { path = "../chart" }
dto = { path = "../dto" }
iex = { path = "../iex" }
serde = { version = "1.0.123", features = ["derive"] }